// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8Pu6dD7-5QT8f427IiZTwp_Mz4DwIahU',
    appId: '1:297020473037:web:05fdcc8ecb3a7e4cdf3384',
    messagingSenderId: '297020473037',
    projectId: 'grocery-shop-cc29d',
    authDomain: 'grocery-shop-cc29d.firebaseapp.com',
    storageBucket: 'grocery-shop-cc29d.appspot.com',
    measurementId: 'G-8Z63CMEP1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCFTAKEaoINBooAZkCDDcSgYHYjMUuZFg',
    appId: '1:297020473037:android:ab20218dc831438cdf3384',
    messagingSenderId: '297020473037',
    projectId: 'grocery-shop-cc29d',
    storageBucket: 'grocery-shop-cc29d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByvpYerZRnrmYGBF01F11nEmVznYRmUlc',
    appId: '1:297020473037:ios:4ba18047dd47491cdf3384',
    messagingSenderId: '297020473037',
    projectId: 'grocery-shop-cc29d',
    storageBucket: 'grocery-shop-cc29d.appspot.com',
    iosClientId:
        '297020473037-qlre62a149p0k9s9jhgv7rddjvf5r8lu.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByvpYerZRnrmYGBF01F11nEmVznYRmUlc',
    appId: '1:297020473037:ios:c9028f3d034f9a1cdf3384',
    messagingSenderId: '297020473037',
    projectId: 'grocery-shop-cc29d',
    storageBucket: 'grocery-shop-cc29d.appspot.com',
    iosClientId:
        '297020473037-rl5u8qmg2a8k826ums6jvdectp2l02nl.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryShop.RunnerTests',
  );
}
